
version: '2'
services:
  volume:
    image: edgexfoundry/docker-edgex-volume
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - /data/db
      - /edgex/logs
      - /consul/config
      - /consul/data
      - /framework/ha
      - /runtime/ha

  consul:
    image: edgexfoundry/docker-core-consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume

  mongo:
    image: edgexfoundry/docker-edgex-mongo
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
    command: --smallfiles

  mongo-seed:
    image: edgexfoundry/docker-edgex-mongo-seed
    container_name: edgex-mongo-seed
    hostname: edgex-mongo-seed
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - mongo

  logging:
    image: edgexfoundry/docker-support-logging
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - consul
      - config-seed
      - mongo
      - mongo-seed 

  metadata:
    image: edgexfoundry/docker-core-metadata
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - consul
      - config-seed
      - mongo
      - mongo-seed
      - logging

  data:
    image: edgexfoundry/docker-core-data
    ports:
      - "48080:48080"
      - "5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - consul
      - config-seed
      - mongo
      - mongo-seed
      - logging

  command:
    image: edgexfoundry/docker-core-command
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - consul
      - config-seed
      - mongo
      - mongo-seed
      - logging
      - metadata
      

networks:
  edgex-network:
    driver: "bridge"
... 
